// SPDX-License-Identifier: Apache-2.0
package com.glyphdialer.core.domain.model

/**
 * A visual-voicemail message from [android.provider.VoicemailContract] where the
 * carrier/OS supports it (§8). When VVM is unsupported the voicemail feature falls
 * back to dialing the carrier voicemail number; that fallback is not modelled here.
 */
data class Voicemail(
    val id: Long,
    val number: PhoneNumber,
    val displayName: String? = null,
    val photoUri: String? = null,
    val timestampMillis: Long,
    val durationSeconds: Long = 0L,
    val isRead: Boolean = false,
    /** content:// URI of the downloaded audio, or null while not yet fetched. */
    val audioUri: String? = null,
    /** True once the audio body has been downloaded locally. */
    val hasContent: Boolean = false,
    /** Optional carrier/engine-provided transcription text. */
    val transcriptionText: String? = null,
    /** Id of a richer [Transcript] generated by our engine, if any. */
    val transcriptId: String? = null,
)
